name: Meson Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        meson_version: ["1.4.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: amitie10g/install-package@v1.2.5
        with:
          apt: build-essential libtool pkg-config lv2-dev meson ninja-build
      - name: Configure Project
        run: meson setup build -Dlv2dir=$HOME/.lv2/
      - name: Build
        run: meson compile -C build
      - name: Install
        run: meson install -C build

      # - name: Run Tests
      #   run: meson test -C build/ -v
      # - name: Upload Test Log
      #   uses: actions/upload-artifact@v4
      #   if: failure()
      #   with:
      #     name: ${{ matrix.os }}_Meson_Testlog
      #     path: builddir/meson-logs/testlog.txt
