name: 'Torture'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        meson_version: ["1.4.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Test
        run: docker build -t quasar-test .
      - name: Run Test
        run: docker run -t quasar-test
